name: task-a cd

on: [ push ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: pytest
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ "3.10", "3.11", "pypy3.10" ]
        exclude:
          - os: macos-latest
            python-version: "3.10"
          - os: windows-latest
            python-version: "3.10"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}  # Changed from '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r ./task_a/requirements.txt
          pip install pytest-html
      - name: Run tests
        run: |
          python3 -m pytest ./task_a/task_a.py --html=report.html --self-contained-html
        continue-on-error: true
      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pytest-report-${{ matrix.os }}-${{ matrix.python-version }}  # Added matrix variables
          path: report.html